### ISSUE TITLE
Using "Cancel" changes the artboard anyway

### ISSUE THREAD

**Issue by ebosse** [daneden/sketch-navigate-artboards#1]
The Cancel function is not working properly. I tend to hit the keyboard shortcut often by mistake and when I press cancel, it takes me to the artboard that is selected by default in the list. Could you fix it?

**Comment by daneden** [comment]
@ebosse I’m not sure I understand your issue—this plugin doesn't have any opportunity to 'Cancel' since it just enables a shortcut to immediately navigate between artboards. Would you mind going into a little more detail? What are you trying to cancel?

**Comment by ebosse** [comment]
Hi,

There is a cancel button (see attached) however when I press it it still
navigates to the selected artboard. I would like to be about to just stay
where I am. I tend to hit the Cmd+E often without intending to navigate
anywhere.

[image: Images intégrées 2]

*--*

Elaine Bossé, M.A.Spécialiste UX /
UX specialist

Tel : 514 982.6560 x 327

________________

Absolunet
MONTREAL - KANSAS CITY - BOISBRIAND
4398 Boulevard Saint-Laurent
Bureau 204, Montréal
Québec  H2W 1Z5

Sans frais : 1.877.979.2276
www.absolunet.com

2017-03-30 16:04 GMT-04:00 Daniel Eden <notifications@github.com>:

**Comment by daneden** [comment]
@ebosse I don't think email attachments work when replying to GitHub issues, would you mind uploading on github.com or providing a link to your screenshot?
