### ISSUE TITLE
Here's a thought  

### ISSUE THREAD

**Issue by YonatanKof** [daneden/sketch-navigate-artboards#2]
First thing, I've missed this behavior from Illustrator, so thanks! It makes me feel more at home :-)

Here's the thought: I believe that the top of the page is the most indicative part of the design, but the plugin behavior is to focus on the middle of the page, and if it's long I won't see the top.

Is there a way to enable the view to snap to the top of the page while navigating? And if so, can you please add it as an optional behavior?

Best wishes,
Yonatan.

**Comment by daneden** [comment]
Hey @YonatanKof! Good suggestion! This is actually how I want the plugin to behave, but I was too lazy to implement it this way. I’ll work on this change now that I’m a little more familiar with the available API!

**Comment by daneden** [comment]
It's also worth noting that navigating artboards is now a native feature of Sketch—use `fn + Left/Right` to move through artboards.
